---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm install
- name: lint
  image: danlynn/ember-cli:3.20.0
  commands:
  - npm run lint
- name: test
  image: danlynn/ember-cli:3.20.0
  failure: ignore
  commands:
  - npm run test:ember
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: npm-release
  image: plugins/npm
  settings:
    token:
      from_secret: npm_access_token
trigger:
  event:
    - tag
---
kind: secret
name: npm_access_token
data: d7368bba-01b6-4fc8-aa34-a4856cb16e28
---
kind: signature
hmac: 68610869bf4ab2f8b668ce06b2320bbe5ffe5ba2eeb8e9f7167dcc785d617845

...
